### ISSUE TITLE
LoRA-GA Tuning Issue: Task Loss Not Working as Expected

### ISSUE THREAD

**Issue by fclearner** [Outsider565/LoRA-GA#5]
Hi,
Thanks for excellent work on LoRA-GA,
I am experiencing an issue while using LoRA-GA for model training. Specifically, the task loss is not decreasing as expected. I would like to seek any advice or tuning tips that might help improve this situation.

Are there recommended parameter settings or tuning strategies?

Current Parameter Settings:

```
init_batch_size: 2
init_iters: 4
init_config:
  mode: "gradient"  # option: "simple", "svd", "gradient"
  lora_A: "unit"  # option: "gaussian", "kaiming", "fan_out_kaiming", "xavier", "zeros", "unit", "orthogonal"
  lora_A_std: 0.01  # only needed when lora_A is "gaussian"
  lora_B: "unit"  # option: "gaussian", "kaiming", "fan_out_kaiming", "xavier", "zeros", "unit", "orthogonal"
  lora_B_std: 0.01  # only needed when lora_B is "gaussian"
  scale: "stable"  # option: "default", "stable", "unit", "normalized", "gd", "weightS"
  stable_gamma: 64  # only needed when scale is "stable"
  direction: "ArB2r"  # option: "ArBr", "A2rBr", "ArB2r"（only needed when mode is "gradient"）
  dtype: "fp32"  # option: "bf16", "fp32"
  norm_clip: false  # norm clipping
```

this is my loss scalars:

<img width="1081" alt="1723421470820" src="https://github.com/user-attachments/assets/a134181f-c158-4b19-8c52-970e0f971e91">

it would be very helpful if you can offer some suggestions!
Thanks!
